// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtPIP5VRshYY6QBtrs89Zaq5Y4Ha5vvE',
    appId: '1:2569042607:web:141590b15956fbecfc725a',
    messagingSenderId: '2569042607',
    projectId: 'mediag-277f9',
    authDomain: 'mediag-277f9.firebaseapp.com',
    storageBucket: 'mediag-277f9.appspot.com',
    measurementId: 'G-FQYPQP466C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApiKKg2P6YI1uWLXaBBsRdMNYg1V6ZKb4',
    appId: '1:2569042607:android:e5921685251ef1d1fc725a',
    messagingSenderId: '2569042607',
    projectId: 'mediag-277f9',
    storageBucket: 'mediag-277f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyn1FnMHQEjO1zt-9vNcRrgzbHuXif2J4',
    appId: '1:2569042607:ios:a0b0fb06e0060e2ffc725a',
    messagingSenderId: '2569042607',
    projectId: 'mediag-277f9',
    storageBucket: 'mediag-277f9.appspot.com',
    iosClientId: '2569042607-ku5beri7913d85263kf3196sq3s7n5fv.apps.googleusercontent.com',
    iosBundleId: 'com.uits47.mediag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyn1FnMHQEjO1zt-9vNcRrgzbHuXif2J4',
    appId: '1:2569042607:ios:c093a923aae6ee08fc725a',
    messagingSenderId: '2569042607',
    projectId: 'mediag-277f9',
    storageBucket: 'mediag-277f9.appspot.com',
    iosClientId: '2569042607-3t8kbj7p4ve38b7lm46t4ia5grtmpk5c.apps.googleusercontent.com',
    iosBundleId: 'com.uits47.mediag.RunnerTests',
  );
}
